// This file is auto-generated. Do not edit manually.
// Generated by build-rules-index.js
import { rulesManager } from "./rules";
import { RuleAddPrefix } from "./addPrefix";
import { RuleAddSuffix } from "./addSuffix";
import { RuleAutomationAutoLink } from "./automationAutoLink";
import { RuleBuildInAutoCompleteModal } from "./buildInAutoCompleteModal";
import { RuleBuildInConcatProperties } from "./buildInConcatProperties";
import { RuleBuildInConstant } from "./buildInConstant";
import { RuleBuildInDateTimeCreated } from "./buildInDateTimeCreated";
import { RuleBuildInDateTimeModified } from "./buildInDateTimeModified";
import { RuleBuildInDefault } from "./buildInDefault";
import { RuleBuildInFileSizeBytes } from "./buildInFileSizeBytes";
import { RuleBuildInFileSizeString } from "./buildInFileSizeString";
import { RuleBuildInFolder } from "./buildInFolder";
import { RuleBuildInFolderFolderNotes } from "./buildInFolderFolderNotes";
import { RuleBuildInFolders } from "./buildInFolders";
import { RuleBuildInFullPath } from "./buildInFullPath";
import { RuleBuildInFullPathExt } from "./buildInFullPathExt";
import { RuleBuildInFullPathExtFolderNotes } from "./buildInFullPathExtFolderNotes";
import { RuleBuildInFullPathFolderNotes } from "./buildInFullPathFolderNotes";
import { RuleBuildInGetProperty } from "./buildInGetProperty";
import { RuleBuildInIsRoot } from "./buildInIsRoot";
import { RuleBuildInLinkToFile } from "./buildInLinkToFile";
import { RuleBuildInName } from "./buildInName";
import { RuleBuildInNameExt } from "./buildInNameExt";
import { RuleBuildInPath } from "./buildInPath";
import { RuleBuildInPathFolderNotes } from "./buildInPathFolderNotes";
import { RuleBuildInRootFolder } from "./buildInRootFolder";
import { RuleBuildInScript } from "./buildInScript";
import { RuleReplaceSpaces } from "./replaceSpaces";
import { RuleReplaceSpecialChars } from "./replaceSpecialChars";
import { RuleToCamelCase } from "./toCamelCase";
import { RuleToLinkMarkdown } from "./toLinkMarkdown";
import { RuleToLinkOriginal } from "./toLinkOriginal";
import { RuleToLinkSimple } from "./toLinkSimple";
import { RuleToLinkWiki } from "./toLinkWiki";
import { RuleToLowerCase } from "./toLowerCase";
import { RuleToOriginal } from "./toOriginal";
import { RuleToPascalCase } from "./toPascalCase";
import { RuleToTitleCase } from "./toTitleCase";
import { RuleToTitleCaseDE } from "./toTitleCaseDE";
import { RuleToTitleCaseEN } from "./toTitleCaseEN";
import { RuleToUpperCase } from "./toUpperCase";

// List of all rule classes
const ruleClasses = [RuleAddPrefix, RuleAddSuffix, RuleAutomationAutoLink, RuleBuildInAutoCompleteModal, RuleBuildInConcatProperties, RuleBuildInConstant, RuleBuildInDateTimeCreated, RuleBuildInDateTimeModified, RuleBuildInDefault, RuleBuildInFileSizeBytes, RuleBuildInFileSizeString, RuleBuildInFolder, RuleBuildInFolderFolderNotes, RuleBuildInFolders, RuleBuildInFullPath, RuleBuildInFullPathExt, RuleBuildInFullPathExtFolderNotes, RuleBuildInFullPathFolderNotes, RuleBuildInGetProperty, RuleBuildInIsRoot, RuleBuildInLinkToFile, RuleBuildInName, RuleBuildInNameExt, RuleBuildInPath, RuleBuildInPathFolderNotes, RuleBuildInRootFolder, RuleBuildInScript, RuleReplaceSpaces, RuleReplaceSpecialChars, RuleToCamelCase, RuleToLinkMarkdown, RuleToLinkOriginal, RuleToLinkSimple, RuleToLinkWiki, RuleToLowerCase, RuleToOriginal, RuleToPascalCase, RuleToTitleCase, RuleToTitleCaseDE, RuleToTitleCaseEN, RuleToUpperCase];

// Register each rule class
ruleClasses.forEach((RuleClass) => {
    const ruleInstance = new RuleClass();
    rulesManager.registerRule(ruleInstance);
});